### ISSUE TITLE
Error:   × parsing configuration

### ISSUE THREAD

**Issue by invent360** [txpipe/dolos#210]
When following the documentation to run dolos as docker container
`docker run -v $(pwd)/config.toml:/etc/dolos/daemon.toml ghcr.io/txpipe/dolos:latest daemon`

where `config.toml`

```
[upstream]
peer_address = "preview-node.world.dev.cardano.org:30002"
network_magic = 2

[rolldb]
path = "./data"
k_param = 1000

[serve.grpc]
listen_address = "[::]:50051"

[byron]
path = "./byron.json"

[logging]
max_level = "debug"
```

i get the following error:
```
Error:   × parsing configuration
  ╰─▶ missing field `storage`
```

**Comment by scarmuega** [comment]
hi, there're a few breaking changes in the latest version of Dolos. Please follow the config docs found here:
https://dolos.txpipe.io/configuration

**Comment by invent360** [comment]
i followed the config you suggested:

`[upstream]
peer_address = "preprod-node.world.dev.cardano.org:30000"
network_magic = 1
is_testnet = true
 
[storage]
path = "./data"
wal_size = 1000
 
[genesis]
byron_path = "./byron.json"
shelley_path = "./shelley.json"
alonzo_path = "./alonzo.json"
 
[sync]
pull_batch_size = 200
 
[submit]
prune_height = 10000
 
[serve.grpc]
listen_address = "[::]:50051"
 
[serve.ouroboros]
listen_address = "localhost:30013"
 
[logging]
max_level = "debug"`

now had the following error

`Error:   × parsing configuration
  ╰─▶ missing field `magic``

**Comment by scarmuega** [comment]
@invent360 I believe this was a problem on my side by not keeping code / docs in sync, I apologize.

Docs are now in sync with the expected config, but since we're making several breaking changes in each version until we stabilize on a v1, the recommended approach to start using Dolos is to run `dolos init` which will prepare the config for you using the correct fields. You can find more info on the quickstart guide: https://dolos.txpipe.io/quickstart
